#
POST https://ap-southeast-1.aws.data.mongodb-api.com/app/data-ncbvy/endpoint/data/v1/action/insertOne
Content-Type: application/json
Access-Control-Request-Headers: *
api-key: QVC1RNf0vbXc7jPPCVTqjqkvrO4Nk7GTHBUPRQwWOVdyBPdpq50SpSQgg4QuGtNP

{
    "collection":"MainTask",
    "database":"BacklogLikeMemo",
    "dataSource":"Cluster0",
    "document": {
        "title": "sample_string2",
        "author": "sample_author3",
        "details": "sample_details4",
        "createTime": "2023-05-07T15:55:00.000+09:00"
    }
}

###

POST https://ap-southeast-1.aws.data.mongodb-api.com/app/data-ncbvy/endpoint/data/v1/action/find
Content-Type: application/json
Access-Control-Request-Headers: *
api-key: QVC1RNf0vbXc7jPPCVTqjqkvrO4Nk7GTHBUPRQwWOVdyBPdpq50SpSQgg4QuGtNP

{
    "collection":"MainTask",
    "database":"BacklogLikeMemo",
    "dataSource":"Cluster0"
}

###

POST https://realm.mongodb.com/api/client/v2.0/app/data-ncbvy/auth/providers/api-key/login
Content-Type: application/json

{
    "key": "QVC1RNf0vbXc7jPPCVTqjqkvrO4Nk7GTHBUPRQwWOVdyBPdpq50SpSQgg4QuGtNP"
}